---

- hosts: Database
  tasks: 
        - name: echo some file
          shell: "ls /tmp/file1"
          register: results
        - debug: 
               var: results
               
        - name: To copy file
          copy: 
                src: /tmp/file1
                dest: /tmp/file1
                owner: akshay
                group: akshay
                mode: '0644'

