---

- hosts: all
  tasks: 
        - name: echo some file
          shell: " id && cp /tmp/file1 file2"
          register: results
        - debug: 
               var: results
               
        - name: To copy file
          copy: 
                src: file2
                dest: /tmp/file1
                owner: akshay
                group: akshay
                mode: '0644'

